// iOS launch images. Without these, an installed PWA shows a blank white screen
// while it boots — the single biggest "this is just a website" tell.
// Generated by scripts/gen-splash.mjs (light + dark, iPhone SE → 16 Pro Max).
const DEVICES = [
  [320, 568, 2], [375, 667, 2], [414, 736, 3], [375, 812, 3],
  [414, 896, 2], [414, 896, 3], [390, 844, 3], [428, 926, 3],
  [393, 852, 3], [430, 932, 3], [402, 874, 3], [440, 956, 3],
] as const;

export default function AppleSplashLinks() {
  return (
    <>
      {DEVICES.flatMap(([w, h, r]) =>
        (["light", "dark"] as const).map((scheme) => (
          <link
            key={`${w}x${h}@${r}-${scheme}`}
            rel="apple-touch-startup-image"
            media={`(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${r}) and (prefers-color-scheme: ${scheme})`}
            href={`/splash/splash-${w}x${h}@${r}x-${scheme}.png`}
          />
        ))
      )}
    </>
  );
}
